CREATE TABLE DATA (
  ID            INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TEMPERATURE   VARCHAR(64),
  HUMIDITY      VARCHAR(64),
  PRESSURE      VARCHAR(64),
  MEASURE       VARCHAR(64)
);

CREATE INDEX DATA_ID_INDEX ON DATA(ID);